### ISSUE TITLE
실행 에러가 납니다. (수정없이 바로 빌드함)

### ISSUE THREAD

**Issue by alphablue** [Jpub/AndroidBNR4#1]
kotlin.UninitializedPropertyAccessException: lateinit property photos has not been initialized
        at com.bignerdranch.android.photogallery.api.FlickrResponse.getPhotos(FlickrResponse.kt:4)
        at com.bignerdranch.android.photogallery.FlickrFetchr$fetchPhotoMetadata$1.onResponse(FlickrFetchr.kt:72)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
        at android.os.Handler.handleCallback(Handler.java:873)

이러한 에러가 뜨면서 초기화를 해야된다는데 코드를 보면 되어 있습니다.

아무런 코드 수정도 하지 않고 바로 빌드해서 실행시켜 본 결과 입니다. 
기종은 note 8 에 api 28버전을 사용하고 있습니다.

저만 그런건지 잘 모르겠으나 확인 해 주실수 있을 까요?

**Comment by alphablue** [comment]
해결했습니다. 문제는 API KEY 발급은 안받고 바로 실행을 해서 생긴 문제였네요.

플리커 사이트에서 key 발급을 받은뒤에 photoInterceptor.kt 에 api를 입력한 후 실행하니 정상 작동이 됩니다.
